export const data = {
  canvas: {
    width: 375,
    height: 667,
  },
  components: [
    {
      component: "v-text",
      events: {},
      groupStyle: {},
      icon: "wenben",
      id: 0,
      isLock: false,
      label: "文字",
      propValue: "双击编辑文字",
      style: {
        color: "",
        fontSize: 14,
        height: 22,
        left: 100.5,
        lineHeight: "",
        opacity: 1,
        rotate: 0,
        textAlign: "",
        top: 101,
        width: 200,
      },
    },
    {
      component: "v-button",
      events: {},
      groupStyle: {},
      icon: "button",
      id: 1,
      isLock: false,
      label: "按钮",
      propValue: "按钮",
      style: {
        backgroundColor: "yellow",
        borderColor: "red",
        color: "green",
        fontSize: 18,
        height: 34,
        left: 140,
        letterSpacing: 0,
        lineHeight: "",
        opacity: 1,
        position: "absolute",
        rotate: 0,
        textAlign: "",
        top: 164,
        width: 100,
      },
    },
  ],
};
